// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/admin/clients": {
            "get": {
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configs"
                ],
                "summary": "getting a list of clients",
                "parameters": [
                    {
                        "type": "string",
                        "description": "authentication\theader",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "the clients for this group",
                        "name": "group",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "client error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    },
                    "500": {
                        "description": "server error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configs"
                ],
                "summary": "posting changes to a client",
                "parameters": [
                    {
                        "type": "string",
                        "description": "authentication\theader",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "json of client",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "client error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    },
                    "500": {
                        "description": "server error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    }
                }
            }
        },
        "/admin/clients/{name}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configs"
                ],
                "summary": "gets a client",
                "parameters": [
                    {
                        "type": "string",
                        "description": "authentication\theader",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "client name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "client error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    },
                    "500": {
                        "description": "server error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configs"
                ],
                "summary": "delete a client by name",
                "parameters": [
                    {
                        "type": "string",
                        "description": "authentication\theader",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "name of the client to delete",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "client error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    },
                    "500": {
                        "description": "server error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    }
                }
            }
        },
        "/admin/groupkeys": {
            "get": {
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configs"
                ],
                "summary": "getting a list of groupkeys",
                "parameters": [
                    {
                        "type": "string",
                        "description": "authentication\theader",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "group the get all keys for",
                        "name": "group",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "client error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    },
                    "500": {
                        "description": "server error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configs"
                ],
                "summary": "creating a new group key",
                "parameters": [
                    {
                        "type": "string",
                        "description": "authentication\theader",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "pem file",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "client error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    },
                    "500": {
                        "description": "server error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    }
                }
            }
        },
        "/admin/groups": {
            "get": {
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configs"
                ],
                "summary": "getting a list of groups",
                "parameters": [
                    {
                        "type": "string",
                        "description": "authentication\theader",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "client error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    },
                    "500": {
                        "description": "server error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configs"
                ],
                "summary": "creating a new group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "authentication\theader",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "group definition",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pmodel.Group"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "client error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    },
                    "500": {
                        "description": "server error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    }
                }
            }
        },
        "/admin/groups/{name}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configs"
                ],
                "summary": "gets a group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "authentication\theader",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "group name",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "client error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    },
                    "500": {
                        "description": "server error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    }
                }
            },
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configs"
                ],
                "summary": "updates a group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "authentication\theader",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "name of the group",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "group definition",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pmodel.Group"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "client error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    },
                    "500": {
                        "description": "server error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configs"
                ],
                "summary": "delete a  group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "authentication\theader",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "name of the group to delete",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "client error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    },
                    "500": {
                        "description": "server error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    }
                }
            }
        },
        "/admin/info": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configs"
                ],
                "summary": "getting service informations",
                "parameters": [
                    {
                        "type": "string",
                        "description": "authentication\theader",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "client error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    },
                    "500": {
                        "description": "server error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    }
                }
            }
        },
        "/admin/playbook": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configs"
                ],
                "summary": "posting the public key of a client certificate for the client",
                "parameters": [
                    {
                        "type": "string",
                        "description": "authentication\theader",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "playbook file",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.Playbook"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "client error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    },
                    "500": {
                        "description": "server error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    }
                }
            }
        },
        "/admin/utils/decodecert": {
            "post": {
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configs"
                ],
                "summary": "decoding a certificate",
                "parameters": [
                    {
                        "type": "string",
                        "description": "authentication\theader",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "pem file",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "client error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    },
                    "500": {
                        "description": "server error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configs"
                ],
                "summary": "login a client to the vault service",
                "parameters": [
                    {
                        "description": "json login",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "token for further processing",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "client error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    },
                    "500": {
                        "description": "server error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    }
                }
            }
        },
        "/login/privatekey/": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configs"
                ],
                "summary": "getting the personal private key of a client certificate",
                "parameters": [
                    {
                        "type": "string",
                        "description": "authentication header",
                        "name": "token",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "client error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    },
                    "500": {
                        "description": "server error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    }
                }
            }
        },
        "/login/refresh": {
            "get": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configs"
                ],
                "summary": "refresh a client to the vault service",
                "parameters": [
                    {
                        "type": "string",
                        "description": "authentication\theader",
                        "name": "refreshtoken",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "new token, refresh token",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "token for further processing",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "client error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    },
                    "500": {
                        "description": "server error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    }
                }
            }
        },
        "/vault/certificate": {
            "post": {
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configs"
                ],
                "summary": "posting a certificate request to this mv service, returning a signed certificate",
                "parameters": [
                    {
                        "type": "string",
                        "description": "authentication\theader",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "pem file",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "client error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    },
                    "500": {
                        "description": "server error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    }
                }
            }
        },
        "/vault/certificate/{name}": {
            "get": {
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configs"
                ],
                "summary": "getting the public key of a client certificate for the named client",
                "parameters": [
                    {
                        "type": "string",
                        "description": "authentication\theader",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "name of the client",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "file"
                        }
                    },
                    "400": {
                        "description": "client error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    },
                    "500": {
                        "description": "server error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    }
                }
            }
        },
        "/vault/groups/crypt": {
            "post": {
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configs"
                ],
                "summary": "posting a crypt message, getting back the result, server side en/decryption",
                "parameters": [
                    {
                        "type": "string",
                        "description": "authentication\theader",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "pem file",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "client error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    },
                    "500": {
                        "description": "server error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    }
                }
            }
        },
        "/vault/groups/keys": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configs"
                ],
                "summary": "posting data to generate a new key for group",
                "parameters": [
                    {
                        "type": "string",
                        "description": "authentication\theader",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "data for creating a new key",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "string"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "client error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    },
                    "500": {
                        "description": "server error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    }
                }
            }
        },
        "/vault/groups/keys/{id}": {
            "post": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configs"
                ],
                "summary": "getting a single key",
                "parameters": [
                    {
                        "type": "string",
                        "description": "authentication\theader",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "id of the key",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "json object of key",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "client error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    },
                    "500": {
                        "description": "server error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    }
                }
            }
        },
        "/vault/msg": {
            "post": {
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configs"
                ],
                "summary": "posting message to be stored securly for group/client",
                "parameters": [
                    {
                        "type": "string",
                        "description": "authentication\theader",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "the message to store",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pmodel.Message"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "id of the message",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "client error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    },
                    "500": {
                        "description": "server error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    }
                }
            }
        },
        "/vault/msg/{id}": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configs"
                ],
                "summary": "getting a single message, if allowed",
                "parameters": [
                    {
                        "type": "string",
                        "description": "authentication\theader",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "id of the message to read",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pmodel.Message"
                        }
                    },
                    "400": {
                        "description": "client error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    },
                    "500": {
                        "description": "server error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    }
                }
            },
            "delete": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configs"
                ],
                "summary": "deleting a single message, if allowed",
                "parameters": [
                    {
                        "type": "string",
                        "description": "authentication\theader",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "id of the message to read",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "nothing",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "client error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    },
                    "500": {
                        "description": "server error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    }
                }
            }
        },
        "/vault/signature/check": {
            "post": {
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configs"
                ],
                "summary": "posting a message to check the signature, getting back the result, server side sing checking",
                "parameters": [
                    {
                        "type": "string",
                        "description": "authentication\theader",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "message to check",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pmodel.SignMessage"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pmodel.SignMessage"
                        }
                    },
                    "400": {
                        "description": "client error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    },
                    "500": {
                        "description": "server error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    }
                }
            }
        },
        "/vault/signature/sign": {
            "post": {
                "consumes": [
                    "application/octet-stream"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "configs"
                ],
                "summary": "posting a message to sign, getting back the result, server side signing",
                "parameters": [
                    {
                        "type": "string",
                        "description": "authentication\theader",
                        "name": "token",
                        "in": "header",
                        "required": true
                    },
                    {
                        "description": "message to sign",
                        "name": "payload",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/pmodel.SignMessage"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/pmodel.SignMessage"
                        }
                    },
                    "400": {
                        "description": "client error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    },
                    "500": {
                        "description": "server error information as json",
                        "schema": {
                            "$ref": "#/definitions/serror.Serr"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.Client": {
            "type": "object",
            "properties": {
                "accesskey": {
                    "type": "string"
                },
                "crt": {
                    "type": "object",
                    "additionalProperties": {}
                },
                "groups": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "hash": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                },
                "kid": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "salt": {
                    "type": "string"
                },
                "secret": {
                    "description": "BEWARE: Only for usage in playbook",
                    "type": "string"
                }
            }
        },
        "model.EncryptKey": {
            "type": "object",
            "properties": {
                "alg": {
                    "type": "string"
                },
                "created": {
                    "type": "string"
                },
                "group": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "key": {
                    "type": "string"
                }
            }
        },
        "model.Group": {
            "type": "object",
            "properties": {
                "isclient": {
                    "type": "boolean"
                },
                "key": {
                    "type": "string"
                },
                "kid": {
                    "type": "string"
                },
                "label": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "model.Playbook": {
            "type": "object",
            "properties": {
                "clients": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Client"
                    }
                },
                "groups": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.Group"
                    }
                },
                "keys": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.EncryptKey"
                    }
                }
            }
        },
        "pmodel.Group": {
            "type": "object",
            "properties": {
                "isclient": {
                    "type": "boolean"
                },
                "label": {
                    "type": "object",
                    "additionalProperties": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                }
            }
        },
        "pmodel.KeyInfo": {
            "type": "object",
            "properties": {
                "alg": {
                    "type": "string"
                },
                "kid": {
                    "type": "string"
                }
            }
        },
        "pmodel.Message": {
            "type": "object",
            "properties": {
                "decrypt": {
                    "description": "True for message decryption and false for message encryption",
                    "type": "boolean"
                },
                "id": {
                    "description": "only set when the AES key is already created",
                    "type": "string"
                },
                "message": {
                    "description": "the message to en/decrypt",
                    "type": "string"
                },
                "origin": {
                    "description": "who sends this message, group name or client name",
                    "type": "string"
                },
                "recipient": {
                    "description": "who should receive this message, group name or client name",
                    "type": "string"
                },
                "type": {
                    "description": "The type of message means group for group messages or private for a private message",
                    "type": "string"
                }
            }
        },
        "pmodel.SignMessage": {
            "type": "object",
            "properties": {
                "keyInfo": {
                    "$ref": "#/definitions/pmodel.KeyInfo"
                },
                "message": {
                    "description": "the message to sign",
                    "type": "string"
                },
                "signature": {
                    "description": "the signature",
                    "type": "string"
                },
                "valid": {
                    "type": "boolean"
                }
            }
        },
        "serror.Serr": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "key": {
                    "type": "string"
                },
                "message": {
                    "type": "string"
                },
                "origin": {
                    "type": "string"
                },
                "service": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "/api/v1",
	Schemes:          []string{},
	Title:            "micro-vault service",
	Description:      "Micro-Vault microservice dead simple key management service without any golden rings, just simple and secure.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
